### ISSUE TITLE
Cannot reproduce Cityscape dataset result

### ISSUE THREAD

**Issue by jamesguoxin** [TuSimple/mx-maskrcnn#85] opened 2017-11-29 09:51 UTC
I've used Resnet 50 as pre-trained backbone, and trained on Cityscape dataset, after 24 epochs (54 hours training), both RCNNLogLoss & MaskLogLoss have been saturated, but the average mAP is only 0.21, much lower than 0.31 as reported. Could you please check if the training script you provided is the same as that you used for training ? Thanks

**Comment by Zehaos** [comment] 2017-11-30 03:40
Closing as duplicate of #59. Feel free to re-open if #59 doesn't slove your problem.

**Closed by Zehaos** 2017-11-30 03:40 UTC
